name: Lottery Analysis

on:
  schedule:
    - cron: '0 10 * * *'  # 每天UTC 10:00运行 (北京时间18:00)
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]
    paths:
      - 'src/**'
      - 'run.py'
      - '.github/workflows/main.yml'

jobs:
  analyze-and-notify:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # 获取完整历史记录，确保版本标签可用
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgomp1  # XGBoost依赖
        
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r src/requirements.txt || pip install \
            pandas>=2.0.3 \
            numpy>=1.24.4 \
            scikit-learn>=1.3.2 \
            requests>=2.31.0 \
            xgboost>=1.7.0 \
            joblib>=1.2.0
        pip list  # 显示已安装的包
        
    - name: Verify imports
      run: |
        python -c "from src.data_processor import add_temporal_features; print('Import check passed')"
        
    - name: Run analysis
      env:
        DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python run.py || (echo "Analysis failed with exit code $?"; exit 1)
        
    - name: Upload logs (on failure)
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: error-logs
        path: |
          src/ml_predictor.log
          models/*.log
        retention-days: 3
