[file name]: .github/workflows/main.yml
[file content begin]
name: Lottery Analysis Pipeline

on:
  schedule:
    - cron: '0 10 * * *'  # 每天UTC 10:00 (北京时间18:00)
  workflow_dispatch:  # 允许手动触发
  push:
    branches: [ main ]

jobs:
  analyze:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        cache: 'pip'
        
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgomp1
        
    - name: Install Python dependencies
      run: |
        pip install --upgrade pip
        pip install -r src/requirements.txt || (
          echo "::warning::Failed to install from requirements.txt, falling back to core dependencies"
          pip install pandas numpy scikit-learn xgboost requests lunarcalendar
        )
        
    - name: Verify imports
      run: |
        python -c "
        from src.data_processor import add_temporal_features
        from src.analysis import LotteryAnalyzer
        from src.utils import send_dingtalk
        print('Import verification passed')
        "
        
    - name: Run analysis
      env:
        DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
      run: |
        python run.py || (
          echo "::error::Analysis failed"
          exit 1
        )
        
    - name: Upload logs
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: analysis-logs
        path: |
          src/ml_predictor.log
          models/training.log
[file content end]
