name: Lottery Analysis

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

jobs:
  analyze-and-notify:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    - run: pip install -r src/requirements.txt
    - run: python run.py
      env:
        DINGTALK_WEBHOOK: ${{ secrets.DINGTALK_WEBHOOK }}
        DINGTALK_SECRET: ${{ secrets.DINGTALK_SECRET }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PWD: ${{ secrets.EMAIL_PWD }}
        EMAIL_RECEIVER: ${{ secrets.EMAIL_RECEIVER }}
